project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "American Idol Data Analysis"
  author:
    - Hailey Weingord (hnw2108)
    - Anusha Nandula (sn3146)
  repo-url: https://github.com/hweingord20/AmericanIdol
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


