# Conclusion

Our goal was to observe the factors that make American Idol popular using the variety of datasets we had about show ratings, songs, judges, auditions, etc. Additionally, we wanted to investigate patterns among the finalists throughout the seasons. We were able to see that viewership was heavily correlated with the judging panel each season. The first panel of judges were the most popular by far and remained consistent for the first 7 seasons. After this original panel left the show, the average viewership drastically decreased. We also noticed that most finalists were from bigger cities along the coasts. This makes sense based on proximity to the audition cities that had the most participants selected to advance to the show - such as LA, San Francisco, and Nashville. 

Throughout our project, we faced some limitations that caused us to shift gears from our initial goals. After we began to make our plots and started exploring the data, we realized that we were missing some data that we needed to analyze specific trends. For example, we couldn’t make use of the songs dataset since it just had individual songs that contestants used and there were no genres given to categorize them by. Also, we only had birthplace and birthdays of the finalists, so we weren’t able to examine these distributions among all contestants. 

Due to these limitations, we learned that we should look at the data we have more carefully before starting the project to ensure that it can address all the questions we have. Next time we do a similar project, we will look into finding multiple data sources that can help us analye the trends we have in mind. Throughout this project, we were also limited by the type of data we chose. It would have been convenient to have more numerical data because it was hard to analyze certain trends through the categorical data that we had. To continue this project in the future, we would definitely look into finding data related to other popular singing competitions, such as The Voice. We could compare popularity of these shows to American Idol and see if the timeline of these shows relates to the downfall of American Idol in more recent years.
